<?php

namespace App\Data\Proxy\__CG__\App\Data\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Study extends \App\Data\Entity\Study implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'comments', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'consultation', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'creationDateTime', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'creator', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'deleted', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'deleter', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'deletionDateTime', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'experiment', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'files', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'id', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'input', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'lastEditionDateTime', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'lastEditor', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'output', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'state', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'version');
        }

        return array('__isInitialized__', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'comments', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'consultation', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'creationDateTime', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'creator', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'deleted', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'deleter', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'deletionDateTime', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'experiment', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'files', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'id', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'input', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'lastEditionDateTime', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'lastEditor', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'output', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'state', '' . "\0" . 'App\\Data\\Entity\\Study' . "\0" . 'version');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Study $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addFile($file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFile', array($file));

        return parent::addFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function delete($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', array($user));

        return parent::delete($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getConsultation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsultation', array());

        return parent::getConsultation();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreator', array());

        return parent::getCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function getExperiment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExperiment', array());

        return parent::getExperiment();
    }

    /**
     * {@inheritDoc}
     */
    public function getFiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiles', array());

        return parent::getFiles();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getInput()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInput', array());

        return parent::getInput();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastEditor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastEditor', array());

        return parent::getLastEditor();
    }

    /**
     * {@inheritDoc}
     */
    public function getOutput()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOutput', array());

        return parent::getOutput();
    }

    /**
     * {@inheritDoc}
     */
    public function isDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDeleted', array());

        return parent::isDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function removeFile($file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFile', array($file));

        return parent::removeFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', array());

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function setComments($comments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComments', array($comments));

        return parent::setComments($comments);
    }

    /**
     * {@inheritDoc}
     */
    public function setConsultation($consultation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConsultation', array($consultation));

        return parent::setConsultation($consultation);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreationDateTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreationDateTime', array());

        return parent::setCreationDateTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreator($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreator', array($user));

        return parent::setCreator($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setExperiment($experiment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExperiment', array($experiment));

        return parent::setExperiment($experiment);
    }

    /**
     * {@inheritDoc}
     */
    public function setInput($file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInput', array($file));

        return parent::setInput($file);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastEditionDateTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastEditionDateTime', array());

        return parent::setLastEditionDateTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastEditor($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastEditor', array($user));

        return parent::setLastEditor($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setOutput($file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOutput', array($file));

        return parent::setOutput($file);
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', array($state));

        return parent::setState($state);
    }

}
