<?php

/*
 * This script defines the constants of the application.
 */

define('CHARACTER_ENCODING_UTF8', 'UTF-8');
define('ERROR_INVALID_INPUT', 'INVALID_INPUT');
define('ERROR_NON_EXISTENT_BACKGROUND', 'NON_EXISTENT_BACKGROUND');
define('ERROR_NON_EXISTENT_CLINICAL_IMPRESSION', 'NON_EXISTENT_CLINICAL_IMPRESSION');
define('ERROR_NON_EXISTENT_CONSULTATION', 'NON_EXISTENT_CONSULTATION');
define('ERROR_NON_EXISTENT_DIAGNOSIS', 'NON_EXISTENT_DIAGNOSIS');
define('ERROR_NON_EXISTENT_EXPERIMENT', 'NON_EXISTENT_EXPERIMENT');
define('ERROR_NON_EXISTENT_FILE', 'NON_EXISTENT_FILE');
define('ERROR_NON_EXISTENT_IMAGE_TEST', 'NON_EXISTENT_IMAGE_TEST');
define('ERROR_NON_EXISTENT_LABORATORY_TEST', 'NON_EXISTENT_LABORATORY_TEST');
define('ERROR_NON_EXISTENT_MEDICATION', 'NON_EXISTENT_MEDICATION');
define('ERROR_NON_EXISTENT_NEUROCOGNITIVE_TEST', 'NON_EXISTENT_NEUROCOGNITIVE_TEST');
define('ERROR_NON_EXISTENT_PATIENT', 'NON_EXISTENT_PATIENT');
define('ERROR_NON_EXISTENT_STUDY', 'NON_EXISTENT_STUDY');
define('ERROR_NON_EXISTENT_TREATMENT', 'NON_EXISTENT_TREATMENT');
define('ERROR_NON_EXISTENT_USER', 'NON_EXISTENT_USER');
define('ERROR_UNAUTHORIZED_USER', 'UNAUTHORIZED_USER');
define('ERROR_UNDEFINED_SERVICE', 'UNDEFINED_SERVICE');
define('ERROR_UNDELIVERED_EMAIL', 'UNDELIVERED_EMAIL');
define('ERROR_UNEXPECTED_ERROR', 'UNEXPECTED_ERROR');
define('GENDER_FEMALE', 'f');
define('GENDER_MALE', 'm');
define('HASH_FUNCTION_SHA256', 'sha256');
define('HASH_FUNCTION_SHA512', 'sha512');
define('HTTP_HEADER_CONTENT_TYPE', 'Content-Type');
define('HTTP_MEDIA_TYPE_JSON', 'application/json');
define('HTTP_METHOD_POST', 'POST');
define('HTTP_STATUS_BAD_REQUEST', 400);
define('HTTP_STATUS_FORBIDDEN', 403);
define('HTTP_STATUS_INTERNAL_SERVER_ERROR', 500);
define('HTTP_STATUS_NOT_FOUND', 404);
define('JSON_STRUCTURE_TYPE_ARRAY', 'array');
define('JSON_STRUCTURE_TYPE_OBJECT', 'object');
define('JSON_STRUCTURE_TYPE_VALUE', 'value');
define('KEY_DERIVATION_ITERATIONS', 64000);
define('LOG_LEVEL_1', 1);
define('LOG_LEVEL_2', 2);
define('LOG_LEVEL_3', 3);
define('LOG_LEVEL_4', 4);
define('OPERATION_MODE_DEBUG', 'debug');
define('OPERATION_MODE_RELEASE', 'release');
define('PARAMETERS_DATABASES', 'databases');
define('PARAMETERS_EMAILS', 'emails');
define('RANDOM_ID_LENGTH', 16);
define('RANDOM_PASSWORD_LENGTH', 64);
define('RESULTS_PER_PAGE', 10);
define('SALT_LENGTH', 64);
define('SESSION_DATA_USER', 'user');
define('SORTING_ORDER_ASCENDING', 'ascending');
define('SORTING_ORDER_DESCENDING', 'descending');
define('USER_ROLE_ADMINISTRATOR', 'ad');
define('USER_ROLE_ANONYMOUS', '__');
define('USER_ROLE_DOCTOR', 'dr');
define('USER_ROLE_OPERATOR', 'op');
