<?php

/*
 * This script defines the constants of the application.
 */

// TODO: some constant could be parameters
// TODO: order better the individuals items

define('DATA_TYPE_BOOLEAN', 'boolean');
define('DATA_TYPE_INTEGER_FIX_VALUES', 'integer_fix_values');
define('DATA_TYPE_INTEGER_RANGE', 'integer_range');

define('ERROR_ALREADY_EXISTING_USER', 'ALREADY_EXISTING_USER');
define('ERROR_CORRUPTED_FILE', 'CORRUPTED_FILE');
define('ERROR_INVALID_INPUT', 'INVALID_INPUT');
define('ERROR_NON_EXISTENT_BACKGROUND', 'NON_EXISTENT_BACKGROUND');
define('ERROR_NON_EXISTENT_CLINICAL_IMPRESSION', 'NON_EXISTENT_CLINICAL_IMPRESSION');
define('ERROR_NON_EXISTENT_CONSULTATION', 'NON_EXISTENT_CONSULTATION');
define('ERROR_NON_EXISTENT_DIAGNOSIS', 'NON_EXISTENT_DIAGNOSIS');
define('ERROR_NON_EXISTENT_EXPERIMENT', 'NON_EXISTENT_EXPERIMENT');
define('ERROR_NON_EXISTENT_FILE', 'NON_EXISTENT_FILE');
define('ERROR_NON_EXISTENT_IMAGE_TEST', 'NON_EXISTENT_IMAGE_TEST');
define('ERROR_NON_EXISTENT_LABORATORY_TEST', 'NON_EXISTENT_LABORATORY_TEST');
define('ERROR_NON_EXISTENT_MEDICATION', 'NON_EXISTENT_MEDICATION');
define('ERROR_NON_EXISTENT_NEUROCOGNITIVE_TEST', 'NON_EXISTENT_NEUROCOGNITIVE_TEST');
define('ERROR_NON_EXISTENT_PATIENT', 'NON_EXISTENT_PATIENT');
define('ERROR_NON_EXISTENT_STUDY', 'NON_EXISTENT_STUDY');
define('ERROR_NON_EXISTENT_TREATMENT', 'NON_EXISTENT_TREATMENT');
define('ERROR_NON_EXISTENT_USER', 'NON_EXISTENT_USER');
define('ERROR_UNAUTHORIZED_USER', 'UNAUTHORIZED_USER');
define('ERROR_UNDEFINED_SERVICE', 'UNDEFINED_SERVICE');
define('ERROR_UNDELIVERED_EMAIL', 'UNDELIVERED_EMAIL');
define('ERROR_UNEXPECTED_ERROR', 'UNEXPECTED_ERROR');

define('GENDER_FEMALE', 'f');
define('GENDER_MALE', 'm');

define('HTTP_STATUS_BAD_REQUEST', 400);
define('HTTP_STATUS_CONFLICT', 409);
define('HTTP_STATUS_FORBIDDEN', 403);
define('HTTP_STATUS_INTERNAL_SERVER_ERROR', 500);
define('HTTP_STATUS_NOT_FOUND', 404);

define('LOG_LEVEL_1', 1);
define('LOG_LEVEL_2', 2);
define('LOG_LEVEL_3', 3);
define('LOG_LEVEL_4', 4);

define('OPERATION_MODE_DEBUG', 'debug');
define('OPERATION_MODE_RELEASE', 'release');

define('RANDOM_ID_LENGTH', 16);

define('RANDOM_PASSWORD_LENGTH', 64);

define('SALT_LENGTH', 64);

define('SEARCH_RESULTS_PER_PAGE', 10);

define('SESSION_DATA_USER', 'user');

define('SORTING_ORDER_ASCENDING', 'ascending');
define('SORTING_ORDER_DESCENDING', 'descending');

define('USER_ROLE_ADMINISTRATOR', 'ad');
define('USER_ROLE_ANONYMOUS', '__');
define('USER_ROLE_DOCTOR', 'dr');
define('USER_ROLE_OPERATOR', 'op');
